
  CREATE TABLE IF NOT EXISTS dev_core.api_bundle(
  	id VARCHAR(40) NOT NULL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
	start_date TIMESTAMP NOT NULL, 
	end_date TIMESTAMP NOT NULL, 
	comments VARCHAR(4000) NOT NULL, 
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	created_by VARCHAR(40), 
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);