CREATE TABLE IF NOT EXISTS dev_core.role (
    id VARCHAR(40) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
	description VARCHAR(4000) NOT NULL,
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dev_core.user_role_relationship (
	user_id VARCHAR(40) NOT NULL,
	role_id VARCHAR(40) NOT NULL,
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(user_id, role_id),
	FOREIGN KEY (role_id) REFERENCES role(id),
	FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS dev_core.org_role_relationship (
	org_id VARCHAR(40) NOT NULL,
	role_id VARCHAR(40) NOT NULL,
	created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(org_id, role_id),
	FOREIGN KEY (role_id) REFERENCES role(id),
	FOREIGN KEY (org_id) REFERENCES organization(id)
);